services:
  api:
    build:
      context: .
      dockerfile: Backend/Backend/Dockerfile
    command: >
      ash start.sh
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/Backend:/app

  db:
    container_name: db
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:

volumes:
  db-data: